---

# Install dependencies
- name: Install dependencies
  package:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ packages }}"

# Create apache2 service
- name: Enable apache2 service
  service:
    name: apache2
    state: started
    enabled: yes

# Create directories
- name: Creates directories
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - "{{ directories }}"

# Config apache
- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify:
    - restart apache
- name: Conf fqdn
  copy:
    content: "ServerName localhost"
    dest: /etc/apache2/conf-available/fqdn.conf
- name: Enable a2enconf
  command: a2enconf {{ item }}
  with_items:
    - fqdn
  notify:
    - restart apache

# VH config
- name: Create Wordpress/Moodle virtual hosts config
  template:
    src: templates/vh.conf.j2
    dest: /etc/apache2/sites-available/agora.conf
  notify:
    - restart apache

- name: Remove default config
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - restart apache

- name: Create symbolic link
  file:
    src: /etc/apache2/sites-available/agora.conf
    dest: /etc/apache2/sites-enabled/agora.conf
    state: link
  notify:
    - restart apache

# Config php
- name: Config php
  command: >
    {{ item }}
  args:
      warn: false
  with_items:
    - "{{ php.commands }}"
  notify:
    - restart apache

# Config opcache
- name: Config opcache
  command: >
    {{ item }}
  args:
      warn: false
  with_items:
    - "{{ opcache.commands }}"
  notify:
    - restart apache
